### ISSUE TITLE
🐛 | Phoniebox-RFID-Modul_RC522 Code 128

### ISSUE THREAD

**Issue by Borlizgaron** [MiczFlor/RPi-Jukebox-RFID#1853] opened 2022-06-28 09:16 UTC
### What I did
Hello!
I have successfully installed my Phoniebox and everything is running, except for the RFID reader RC522. It shows as disabled in the web interface under settings. It can be activated, but then does not respond. When I update the web interface, the reader is disabled again.

### What happened

I used this https://github.com/MiczFlor/RP...ponents/rfid-reader/RC522 and startet the Code:

`sudo sh RPi-Jukebox-RFID/components/rfid-reader/RC522/setup_rc522.sh`

The following error message:

`Command "git clone -q git://github.com/ondryaso/pi-rc522.git /tmp/pip-install-attrnxz5/pi-rc522" failed with error code 128 in None`

Can anyone help me? Is something wrong with git? Is something out of date with python?

**Comment by s-martin** [comment] 2022-07-02 20:32
Issue was fixed in https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/1791, but is not yet on master.

**Comment by s-martin** [comment] 2022-07-02 20:33
Duplicate of #1721

**Comment by vitospinelli** [comment] 2022-08-16 14:34
Manually installing RC522 following exactly these instructions solved the issue for me:

https://github.com/pimylifeup/MFRC522-python

**Comment by s-martin** [comment] 2022-08-20 11:34
Fixed by #1791, but not merged to master yet.

**Closed** 2022-08-20 11:34 UTC
Labels: bug, duplicate
