### ISSUE TITLE
High CPU load by daemon_rfid_reader.py and MFRC522

### ISSUE THREAD

**Issue by kaoz3000** [MiczFlor/RPi-Jukebox-RFID#275] opened 2018-10-20 21:25 UTC
Hi,
I'm using the MFRC522 Module with the scripts from @keinkurt: https://github.com/keinkurt/RPi-Jukebox-RFID/tree/MFRC255/scripts on a Raspberry Pi Zero W
I just recognize that the daemon generates a pretty high CPU load between 50–80%:
`pi         486 **80.4**  1.7  11608  7624 ?        Rs   20:47  17:29 /usr/bin/python2 /home/pi/RPi-Jukebox-RFID/scripts/daemon_rfid_reader.py`
This is much more then mpd, which make about 7–10%

Maybe communicate with the reader less often?

**Comment by varac** [comment] 2018-11-05 20:46
Lower the CPU load would be great indeed.
The problem is that the used [MFRC522.py](https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/master/scripts/MFRC522.py) class comes from the [MFRC522-python](https://github.com/mxgxw/MFRC522-python) project. This project has anunresolved issue with [high CPU load](https://github.com/mxgxw/MFRC522-python/issues/17) because it's not possible to use interrupts easily to listen for events, and the only way to read tags is a [nasty while loop](https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/master/scripts/daemon_rfid_reader.py#L12), which looks for tags over and over again.
Adding a `time.sleep(0.3)` in this loop will lower the CPU load, but it's still not ideal.

The solution would be to migrate to the [pi-rc522](https://github.com/ondryaso/pi-rc522) class, which solved this issue by [adding support for listening on events](https://github.com/ondryaso/pi-rc522/issues/9) and introduced a `wait_for_tag()` function which just waits until a tag is detected.
Moving from a simple while loop in a different project to  `wait_for_tag()` in a different project decreased CPU load from 80% to 1-2% with this class!

**Comment by varac** [comment] 2018-11-05 20:48
@keinkurt thx for bringing RC522 support to this project - don't you experience this high CPU load issue yourself ?

**Comment by varac** [comment] 2018-11-05 20:51
Just for the numbers, adding a `time.sleep(0.3)` as described above decreased the CPU load at my system (rpi 2) from 100% to 40%.

**Comment by fenkman** [comment] 2018-11-24 23:49
> Lower the CPU load would be great indeed.
> The problem is that the used [MFRC522.py](https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/master/scripts/MFRC522.py) class comes from the [MFRC522-python](https://github.com/mxgxw/MFRC522-python) project. This project has anunresolved issue with [high CPU load](https://github.com/mxgxw/MFRC522-python/issues/17) because it's not possible to use interrupts easily to listen for events, and the only way to read tags is a [nasty while loop](https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/master/scripts/daemon_rfid_reader.py#L12), which looks for tags over and over again.
> Adding a `time.sleep(0.3)` in this loop will lower the CPU load, but it's still not ideal.
> 
> The solution would be to migrate to the [pi-rc522](https://github.com/ondryaso/pi-rc522) class, which solved this issue by [adding support for listening on events](https://github.com/ondryaso/pi-rc522/issues/9) and introduced a `wait_for_tag()` function which just waits until a tag is detected.
> Moving from a simple while loop in a different project to `wait_for_tag()` in a different project decreased CPU load from 80% to 1-2% with this class!

I just submitted a pull request ( #345) doing what you suggested. Thanks for the tip. Saved my Pi-zero-based project.

**Comment by MiczFlor** [comment] 2018-11-25 09:51
Hi, I merged this with the develop branch
https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/345
and it will go to the master branch soonish. Please test develop, if this works for you. My fear, that happened before: the merge will break all USB RFID readers - and that caused me sleepless nights and unnecessary work. that happened before. See: 
https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/231

**Comment by varac** [comment] 2018-11-27 00:13
I am successfully using develop together with my MFC522 reader.
I needed to do 2 adjustments:

- [Use Reader.py.experimental as Reader.py](https://github.com/varac/RPi-Jukebox-RFID/commit/4e276faefde257d6d35856f6156f36174648fbd4)
- [Let daemon_rfid_reader.py work with Reader.py.experimental](https://github.com/varac/RPi-Jukebox-RFID/commit/f459eb4a4e66e8a7852c95fbf76cb00b53a010a1)

So @MiczFlor  please judge yourself my commits, I'm not sure how to do a proper PR since I don't know if `Reader.py.experimental` will replace the current `Reader.py`.

Btw, the CPU usage improvements are great due to the new use of `pi-rc522` and `wait_for_tag()` !

**Comment by cubertt** [comment] 2018-11-27 18:21
i used the master classic Version with the deamon_rfid_reader.py from the Version of Kein [Kurt  ](https://github.com/keinkurt/RPi-Jukebox-RFID/tree/MFRC255/scripts) successfully.

The orginal deamon_rfid_reader.py gives the following error:

pi@raspberrypi:~/RPi-Jukebox-RFID/scripts $ python daemon_rfid_reader.py
/home/pi/RPi-Jukebox-RFID/scripts
Traceback (most recent call last):
  File "daemon_rfid_reader.py", line 14, in <module>
    cardid = reader.readCard()
AttributeError: 'Reader' object has no attribute 'readCard'
pi@raspberrypi:~/RPi-Jukebox-RFID/scripts $

> Btw, the CPU usage improvements are great due to the new use of pi-rc522 and wait_for_tag() 
> 

Yeah this is great!

**Comment by varac** [comment] 2018-11-27 21:36
@cubertt See how to solve the `Reader' object has no attribute 'readCard'` error in [this commit](https://github.com/varac/RPi-Jukebox-RFID/commit/f459eb4a4e66e8a7852c95fbf76cb00b53a010a1), l. 14.

**Comment by fenkman** [comment] 2018-11-27 21:41
Thank you for merging this so quickly and thank you for testing. Unfortunately I cannot verify USB readers - not having one and going for the seemingly cheaper RC-522 module was the reason for me to work on this anyway :-)

> Btw, the CPU usage improvements are great due to the new use of pi-rc522 and wait_for_tag() !

All the credit goes to you @varac for pointing us in the right direction.

One caveat to be mentioned here: The connection layout for the RC-522 that you find all over the internet is not sufficient to make this work. You have to connect the RC-522 IRQ pin with GPIO25 to make this work as described here: [pi-rc522](https://github.com/ondryaso/pi-rc522)

**Comment by Ardios** [comment] 2018-12-03 22:17
It doesn't work on me. After a fresh installation don't get my reader correctly activated anymore he deactivates himself after I try to read a card

Has anyone tried this with the current version 1.1.8-rc3 classic?

**Comment by MiczFlor** [comment] 2018-12-04 11:50
Please read this
https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/RFID-Reader-Special
I hope that helps.

**Comment by Ardios** [comment] 2018-12-04 12:01
Thanks @MiczFlor

I have already tried this manual but as soon as I try to read a card it's over.

**Comment by alex-voigt** [comment] 2018-12-08 18:50
I can't get it to work as well.

I have a RC522 module that did not work with the latest version of the install script. After reading here #11 and switching to the Version-1.1.5-dynamicRFIDreader branch I could register the device and use it. But CPU load was so high that my pi couldn't play audio from Spotify without interruption.

So I checked out the develop branch and now the reader doesn't work again.
Running `RegisterDevice.py` results in an empty reader list.

The additional pin is connected.

@varac Could you please help on how to set up? The changes suggested didn't work for me. But they don't seem to be the problem right now because the reader is not found at all. Setting the device in deviceName.txt manually also didn't work.

**Comment by alex-voigt** [comment] 2018-12-08 20:05
Ok, I got it working now. Using the `get_devices` method from the Reader did the trick...

https://github.com/alex-voigt/RPi-Jukebox-RFID/commit/aca45199ae742b306a8833f15412146448fbff00

**Comment by varac** [comment] 2018-12-08 20:35
@alex-voigt Have a look at my [`varac` branch](https://github.com/varac/RPi-Jukebox-RFID/tree/varac).
This is how I got it working.

**Comment by MiczFlor** [comment] 2018-12-16 17:10
Hi @Ardios @alex-voigt @fenkman 
I merged alex-voight's pull request to `develop` branch. Please check if this works for you now, before I merge this to master.
Thanks for the input, support and good ideas!

**Comment by fenkman** [comment] 2018-12-18 10:46
I checked out the most recent develop branch and it (still) works for me. Thanks for all the good work! :thumbsup:

**Closed** 2018-12-25 12:48 UTC
