### ISSUE TITLE
ipv6 nginx webapp does not start

### ISSUE THREAD

**Issue by sweetmeats83** [MiczFlor/RPi-Jukebox-RFID#2251] opened 2024-02-11 06:30 UTC
when using the single line install i chose not to use ipv6. Which cause nginx webapp not to start. I edited the nginx site enabled default and removed # listen [::]:80;

**Comment by AlvinSchiller** [comment] 2024-02-11 07:40
Duplicate of #1889

**Comment by AlvinSchiller** [comment] 2024-02-11 23:05
fixed with #2254

**Closed by AlvinSchiller** 2024-02-11 23:05 UTC
Labels: bug, duplicate, future3
