### ISSUE TITLE
Missing Feature Delete Directory

### ISSUE THREAD

**Issue by Hans-Haefner** [MiczFlor/RPi-Jukebox-RFID#651] opened 2019-12-07 07:00 UTC
I miss a way to delete an entire directory or I just overlook what?

**Comment by ctietze** [comment] 2019-12-09 20:24
Hi @Hans-Haefner ,
as far as I know deleting folders is only possible via SSH or via SAMBA. Within the webapp you can only delete single tracks.

BR Clemens

**Comment by Hans-Haefner** [comment] 2019-12-11 16:34
Would be nice if something would be installed, there are aspirations to it?

**Comment by MiczFlor** [comment] 2019-12-13 22:14
Yep, would be nice, won't be this christmas, though ;)

**Comment by Ardios** [comment] 2019-12-19 12:02
Hey all,

at first, sorry for my broken english.

@Hans-Haefner 
I added a file manager maybe it will help you, here is the link:

[https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/510](https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/510)

**Comment by Erechtheus** [comment] 2019-12-22 20:05
@Ardios It might make sense to add your file manager as a pull request?  

BTW: Duplicate of #380

**Comment by s-martin** [comment] 2020-04-12 20:18
Closing as it’s a duplicate of #380

**Closed by s-martin** 2020-04-12 20:18 UTC
Labels: duplicate, enhancement
