### ISSUE TITLE
Short Spotify tracks doesn‘t work

### ISSUE THREAD

**Issue by Simse90** [MiczFlor/RPi-Jukebox-RFID#1039] opened 2020-07-09 19:17 UTC
Spotify tracks which are smaller than 60 seconds doesn‘t work. I tried it with several tracks and playlists and have on all the same behaviour. 
Offline tracks are working pretty good. 
It doesn’t matter if I play them from a linked RFID card or via the Webinterface Iris. 

I tried it with my Phoniebox and a second raspberry with a second SD card and another Spotify premium account (complete new system) and it has the same behaviour. 

I think this issue is related to changes from Spotify. 
Another person have exactly geb same problem like me. 

Would be great if this problem could be fixed. 

Thanks

**Comment by s-martin** [comment] 2020-07-09 19:40
Maybe related to #1034

**Comment by s-martin** [comment] 2020-07-09 19:57
Please close this, if you think this is a duplicate of #1034.

**Closed** 2020-07-09 20:05 UTC
Labels: bug, duplicate, ext dependency, investigation needed, spotify edition
